// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Motd() {
  return window['go']['main']['Motd']['Motd']();
}

export function Platform() {
  return window['go']['main']['Motd']['Platform']();
}

export function Speed() {
  return window['go']['main']['Motd']['Speed']();
}
