// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Motd():Promise<any>;

export function Platform():Promise<string>;

export function Speed():Promise<number>;
